#############################################################################
# Makefile for building: Snake5.app/Contents/MacOS/Snake5
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  Snake5.pro
# Template: app
# Command: /Users/apple2/Qt5.6.3/5.6.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile Snake5.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/Headers -I../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers -I../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang -F/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib
QMAKE         = /Users/apple2/Qt5.6.3/5.6.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Snake51.0.0
DISTDIR = /Users/apple2/C++Examples/Snake5/.tmp/Snake51.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Snake.cpp qrc_media.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		Snake.o \
		qrc_media.o \
		moc_mainwindow.o
DIST          = ../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf \
		Snake5.pro mainwindow.h \
		Snake.h main.cpp \
		mainwindow.cpp \
		Snake.cpp
QMAKE_TARGET  = Snake5
DESTDIR       = 
TARGET        = Snake5.app/Contents/MacOS/Snake5


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d Snake5.app/Contents/MacOS/ || mkdir -p Snake5.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Snake5.pro ../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf \
		Snake5.pro \
		media.qrc \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile Snake5.pro
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/qdevice.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/device_config.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/unix.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/mac.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/macx.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/qconfig.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/spec_post.prf:
../.qmake.stash:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/default_post.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/qt.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/resources.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/moc.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/uic.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/yacc.prf:
../../Qt5.6.3/5.6.3/clang_64/mkspecs/features/lex.prf:
Snake5.pro:
media.qrc:
../../Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile Snake5.pro

qmake_all: FORCE

Snake5.app/Contents/PkgInfo: 
	@test -d Snake5.app/Contents || mkdir -p Snake5.app/Contents
	@$(DEL_FILE) Snake5.app/Contents/PkgInfo
	@echo "APPL????" > Snake5.app/Contents/PkgInfo
Snake5.app/Contents/Resources/empty.lproj: 
	@test -d Snake5.app/Contents/Resources || mkdir -p Snake5.app/Contents/Resources
	@touch Snake5.app/Contents/Resources/empty.lproj
	
Snake5.app/Contents/Info.plist: 
	@test -d Snake5.app/Contents || mkdir -p Snake5.app/Contents
	@$(DEL_FILE) Snake5.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Snake5,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Snake5,g" -e "s,@LIBRARY@,Snake5,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang/Info.plist.app >Snake5.app/Contents/Info.plist

all: Makefile \
		Snake5.app/Contents/PkgInfo \
		Snake5.app/Contents/Resources/empty.lproj \
		Snake5.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents media.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h Snake.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp Snake.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Snake5.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_media.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_media.cpp
qrc_media.cpp: media.qrc \
		images/head.png \
		images/apple.png \
		images/bullet.png \
		images/buttonCover.png \
		images/button.png \
		images/dot.png \
		sounds/hdl.mp3
	/Users/apple2/Qt5.6.3/5.6.3/clang_64/bin/rcc -name media media.qrc -o qrc_media.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		mainwindow.h
	/Users/apple2/Qt5.6.3/5.6.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/mkspecs/macx-clang -I/Users/apple2/C++Examples/Snake5 -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers -F/Users/apple2/Qt5.6.3/5.6.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/apple2/Qt5.6.3/5.6.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		Snake.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

Snake.o: Snake.cpp ../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		Snake.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.6.3/5.6.3/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Snake.o Snake.cpp

qrc_media.o: qrc_media.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_media.o qrc_media.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

